### ISSUE TITLE
Thanks for your awesome addons!And I have a problem

### ISSUE THREAD

**Issue by breezeit** [ijgnd/anki__editor__apply__font_color__background_color__custom_class__custom_style#1]
![Snipaste_2019-04-19_21-17-21](https://user-images.githubusercontent.com/17754387/56425955-ebd43b00-62e8-11e9-933e-14a139cf077d.png)
![Snipaste_2019-04-19_21-20-29](https://user-images.githubusercontent.com/17754387/56425970-fabaed80-62e8-11e9-8fe6-d80369d7976d.png)
The class not working.Background and foreground works well.
My system is win10 64bit,and anki 2.0.52.
Thanks for your awesome addons,again!I have try multime colored addons,yours is the best for time saving.

**Comment by ijgnd** [comment]
Thanks for your report. Could you add some information:

- Did you add .class1 to two style sheets and restart Anki? For details see the section `# styling with "class"` in the description on ankiweb (or [here](https://github.com/ijgnd/anki__editor__apply__font_color__background_color__custom_class__custom_style/blob/aa63a552a306d2196c84bfbaf3732a481e7a9967/ankiweb.html#L20)).
- If you did this: Does the add-on "Customize Editor Stylesheet" work in general in your installation?
- If it still doesn't work: Which are your add-ons? Could you copy and paste the html source code from the bottom of your first screenshot (to make sure I don't have a typo).

I typed this html source code into a field in my Anki 2.0.52 on Windows 10 Pro 1809 that has "Customize Editor Stylesheet" installed.  

In my `_editor.css` I set

``` css
.class1{
   color: magenta;
   font-style: italic;
   font-family:monospace;
}
```

Now it looks like this for me:

![anki2052](https://user-images.githubusercontent.com/40218852/56427235-6be3ac00-62bb-11e9-9c55-b060ad545d87.png)

The html source code is this:
``` html
some_text_before<span class="class1"><span style="background-
color#00ff00">01</span>2<span 
style="color:#ff0000">34</span>56</span><span 
class="class1">789</span>some_text_after
```

**Comment by breezeit** [comment]
Thanks！It worked！
I have make a lots mistake in the details.
![Snipaste_2019-04-21_09-17-16](https://user-images.githubusercontent.com/17754387/56464213-0a385480-6417-11e9-963a-a184107eba97.png)
![Snipaste_2019-04-21_09-17-45](https://user-images.githubusercontent.com/17754387/56464214-0ad0eb00-6417-11e9-8d21-3bd8d5491ab7.png)
