### ISSUE TITLE
Bug - attempt to change hotkey for font size

### ISSUE THREAD

**Issue by DRroscoe** [ijgnd/anki__editor__apply__font_color__background_color__custom_class__custom_style#10]
I received the following bug when trying to change the hotkey for font size to 130%

Debug info:
Anki 2.1.26 (70784154) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 7
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-05-30 04:08:38

Caught exception:
Traceback (most recent call last):
  File "C:\Users\Ronil Patel\AppData\Roaming\Anki2\addons21\1899278645\confdialog_Fontsize.py", line 62, in accept
    "Text_in_menu_styling": self.return_font_size(),
  File "C:\Users\Ronil Patel\AppData\Roaming\Anki2\addons21\1899278645\confdialog_Fontsize.py", line 53, in return_font_size
    return font.rstrip(";").lstrip("font-size:")
AttributeError: 'tuple' object has no attribute 'rstrip'

**Comment by ijgnd** [comment]
Thanks for the report. You found a bug. I forgot to remove a comma. The quickest fix is to remove the trailing comma from line 52 in the file confdialog_Fontsize.py. I mean [this line](https://github.com/ijgnd/anki__editor__apply__font_color__background_color__custom_class__custom_style/blob/9fd305c1bf174eea23577b001973baa89d11e187/src/confdialog_Fontsize.py#L52). 
Does this work?

**Comment by ijgnd** [comment]
and thanks for testing: All bug reports from you are very welcome. If you have improvements for my texts or descriptions these are also very welcome.
