### ISSUE TITLE
Overwrites "Preferences" action on mac

### ISSUE THREAD

**Issue by hgiesel** [ijgnd/anki__editor__apply__font_color__background_color__custom_class__custom_style#12]
In the newest version (that's also on AnkiWeb), when I try to open the Anki Preferences, I instead get the config window for this addon.

I cannot say, whether the same happens on other platforms though.

**Comment by ijgnd** [comment]
I just saw your mail. Thanks for letting me know. That's pretty bad.

I just installed the add-on on a Mac where I have the anki version "2.1.26 alternate". After restarting I don't notice a problem: Cmd+P open the Anki Preferences and from the menu bar "Anki->Einstellungen" also opens it for me. 

I'll have another look at the source code tonight but as far as I see I didn't change anything related to this recently.

It would help a lot if you could rule out an interaction with other add-ons: So if the add-on "editor: apply font color, background color, custom class, custom style" is the only one installed a) cmd+p and b) "Anki->Einstellungen" open your Anki Preferences/Einstellungen.  

Which Anki version do you use on which Mac version? Maybe I can get may hands on a similar machine tomorrow.

Again, thanks for all your help.

**Comment by hgiesel** [comment]
It's definitely this add-on.
And I figured out why. It is [this line](https://github.com/ijgnd/anki__editor__apply__font_color__background_color__custom_class__custom_style/blob/master/src/__init__.py#L234).

And now this sound like I'm going crazy, but: It's the name of the menu item. I tried changing the menu item name, and as soon as I removed the "Configure", it worked fine!

Then I tried experimenting: Changing the menu item to "Confi" was fine, "Config" already caused the bug. However `f"{addonname} Config"` was fine.
It seems like the menu item is not allow ist not allowed to start with the 6 letters "Config". Even the case doesn't matter "cOnFig" causes the bug, too.

I have my set Mac set to English. It seems like yours is set to German. Maybe this changes something. However it's super weird.

**Comment by ijgnd** [comment]
It's the language. After switching to English (US and UK) the menu entry is captured by my add-on also on my machine. Cmd+P still works. 

the main window is based on main.ui and it contains a suspicious "statusTip" with the text [Configure interface language and options](https://github.com/ankitects/anki/blob/772c7a945c25e2134169f08b2307814bf2223377/qt/designer/main.ui#L112) for the Preferences. Each menu entry is a "QAction" and the statustip is [described as](https://doc.qt.io/qt-5/qaction.html#statusTip-prop): "The status tip is displayed on all status bars provided by the action's top-level parent widget." My understanding of this description is that this shouldn't influence other QActions ?

Most of all: Thank you very much for notifying me and figuring this out so quickly.

I just uploaded a new version to ankiweb. For me it's fixed.  Could you update and try again and let me know if it's also fixed for you?

**Comment by hgiesel** [comment]
Yep, it works fine now! Thanks for the quick action.
