### ISSUE TITLE
hotkeys no longer working

### ISSUE THREAD

**Issue by 75462565374252** [ijgnd/anki__editor__apply__font_color__background_color__custom_class__custom_style#31]
Hello, I have lots of hotkeys set up for this add-on, like alt+d or alt+r. They no longer work, probably since I updated to 2.1.30 (not sure).

I tried different combinations and can't get it to work. The multi-button hotkey still works though.

Platform: MacOS

**Comment by ijgnd** [comment]
The shortcut "Alt+R" has never worked for me. "Alt+D" has always worked for me up to 2.1.30. 

The following default shortcuts work in 2.1.26 but not in 2.1.30 for me:
    - alt+q
    - alt+w
    - shift+alt+f
    - shift+alt+5
So I can imagine that other shortcuts won't work either. I would just try other combinations. The majority of shortcuts should still work. 

I have no idea these don't work anymore, as far as I see there were no changes in the Anki source code (i.e. in editor.py and addcards.py) that could have this effect. So it should be about the underlying components used (pyqt/qtwebengineview). There's nothing I can do about this.

&nbsp;

But the most common problem is conflicting add-ons. So I would disable all other add-ons, restart and try again. If some shortcuts work then, it's an add-on conflict. So enable a few add-ons, restart, and try again. Repeat this a few times until you identify the conflict, then chose which add-on is more important to you.

**Comment by 75462565374252** [comment]
Thanks for the quick reply. The conflict seems to be with "GODMODE: faster shortcuts and cloze switching" add-on.

All shortcuts except alt+p work if I disable that addon. I use alt+d, b, r, p, o, g, h, l.

**Comment by ijgnd** [comment]
Strange. "Alt+P" works for me in 2.1.30.

I'm closing this for now.
