### ISSUE TITLE
The name of this addon

### ISSUE THREAD

**Issue by hgiesel** [ijgnd/anki__editor__apply__font_color__background_color__custom_class__custom_style#35]
Something that bothered me for sometime, is the name of this add-on.
I wonder how you think about renaming it a little bit succinctly.

For example take the beginning, and the end, and go with "Editor Apply Custom Styles".
This way "custom styles" can include all the other things mentioned (font color, custom class, etc.).

I like descriptive names, but to this day my brain refuses to memorize the name of this add-on ^^;

**Comment by ijgnd** [comment]
I think the current name is far from perfect. 

I just wanted a discoverable name. I also don't know the official name by heart. I thought that people who search the add-on listing for font, background, or color should find it.

Few users know the term "editor". So I can probably remove it and "apply" is superfluous. How do you like "Custom Styles (font color, background colour, classes, wrapping)" or "Styling (font color, background colour, classes, etc.)" So the official name is short but there's an explanation in parentheses. Though this still lacks your wrapping addition.

Ankiweb has a 60 character limit for add-on names.

**Comment by hgiesel** [comment]
I think "Custom Styles (font color, background colour, classes)" would work best,  just "Styling" is a bit too minimalistic imo. I don't think we need the "wrapping". Just by itself, it's not really an attractive feature, and otherwise I probably guided them towards this add-on from somewhere else anyway.

**Comment by ijgnd** [comment]
I just uploaded your config window changes from 2020-08 (thanks!) and renamed the add-on.
