### ISSUE TITLE
Passing over ownership of the Ankiweb listing

### ISSUE THREAD

**Issue by hgiesel** [ijgnd/anki__editor__apply__font_color__background_color__custom_class__custom_style#36]
Hi,
we've already talked about this some time ago, are you still up for it?
I see the need for several fixes, and I don't want to force the whole uploading to you every single time, especially if I introduce stupid subtle bugs.

If yes, I would post the request on the Anki forum itself.

**Comment by ijgnd** [comment]
Yes, I still think it's a good idea.

link: [original discussion](https://github.com/ijgnd/anki__editor__apply__font_color__background_color__custom_class__custom_style/pull/29#issuecomment-674121480)

**Comment by ijgnd** [comment]
With your first new release could you update the description of the add-on about the change in maintainership somewhere? If you think the add-on is good enough to include your kofi/patreon please do it. 

I think the ankiweb listing should an explanation about copying the config to a different device. I only thought of this after an issue was opened about it this week. I wrote a guide [here](https://github.com/ijgnd/anki__editor__apply__font_color__background_color__custom_class__custom_style/issues/37#issuecomment-692527348). 

Do you get notifications about all the new issues in this repo and the anki forum listing? I want to be sure you get all notifications before I start ignoring messages. I saw that Damien also set you as the thread creator in the forum which should automatically subscribe you to the topic but who knows ... Also there were new messages yesterday shortly before it was transferred to you.

**Comment by hgiesel** [comment]
I get all the notifications, I checked.
I updated the Ankiweb listing to mention me as the maintainer.

Regarding transferring the config: That will probably be the first thing I majorly refactor, and then I will also update the Ankiweb listing accordingly, maybe giving a short picture tutorial.
