### ISSUE TITLE
issue creating text wrapper

### ISSUE THREAD

**Issue by TowelSniffer** [ijgnd/anki__editor__apply__font_color__background_color__custom_class__custom_style#39]
trying to add a text wrapper shows a tiny empty window as shown:

![image](https://user-images.githubusercontent.com/52064198/93532687-6b7c9400-f939-11ea-94d0-2a1bee1b2d13.png)

**Comment by TowelSniffer** [comment]
Installing the pre-release is the fix here https://github.com/ijgnd/anki__editor__apply__font_color__background_color__custom_class__custom_style/releases

**Comment by ijgnd** [comment]
Thanks for reporting this issue. The new maintainer @hgiesel recently improved the config dialog a lot with the new tabbed interface. Hopefully it's only a small bug or typo we introduced when applying these changes.

The pre-release you downloaded is an old test release that misses some of the recent improvements. So I'll reopen the bug. 
 In the long run you should get beck to the regular ankiweb releases.

**Comment by TowelSniffer** [comment]
ok thanks for letting me know, I assumed the pre-release was more of a beta.

**Comment by hgiesel** [comment]
I was already aware of the the bug, I'll sit down to it later today.

**Comment by hgiesel** [comment]
@TowelSniffer I just pushed a new version, which should fix this bug.

**Comment by TowelSniffer** [comment]
seems to be fixed nice work.
