### ISSUE TITLE
ankiweb: raise minimum version required to 2.1.28

### ISSUE THREAD

**Issue by ijgnd** [ijgnd/anki__editor__apply__font_color__background_color__custom_class__custom_style#40]
the add-on now uses the gui_hook [`main_window_did_init`](https://github.com/ijgnd/anki__editor__apply__font_color__background_color__custom_class__custom_style/blob/61fbedf4943a85cf2c9d1215fe512c25df05fb67/src/main_window.py#L4) which was introduced on [2020-05-28](https://github.com/ankitects/anki/commit/6147356) and released with 2.1.28.

source: [reddit post](https://www.reddit.com/r/Anki/comments/ivz380/error_loading_custom_styles_addon/)

**Comment by hgiesel** [comment]
I solved this for now by simply going back to the old-style hook.

I imagine when I'll work some more on the add-on now, I will find many more appropriate places for new hooks, which I'll then add to Anki. When switching to those I'll try to leave it at one breaking release, rather than several.
