### ISSUE TITLE
2.1.41+ wrong colors in editor and in actual card 

### ISSUE THREAD

**Issue by chrisnerio** [ijgnd/anki__editor__apply__font_color__background_color__custom_class__custom_style#48]
Noticed it after 2.1.41

Have only tried this on night mode.
Attached are my settings for the two color codes and two pictures on how should look like (google search).
I also reproduced the problem in an attached video.
<img width="723" alt="Green Color on Settings" src="https://user-images.githubusercontent.com/63787525/115609753-8fc49880-a2ad-11eb-94ef-43b0698df9c8.png">
<img width="743" alt="Pink Color on Settings" src="https://user-images.githubusercontent.com/63787525/115609756-905d2f00-a2ad-11eb-8b1d-e0bc3db8f3fe.png">
<img width="317" alt="Pink" src="https://user-images.githubusercontent.com/63787525/115609757-905d2f00-a2ad-11eb-9fa7-caf7c20bbd58.png">
<img width="300" alt="Green" src="https://user-images.githubusercontent.com/63787525/115609759-90f5c580-a2ad-11eb-93ee-8f4b8bf15cd2.png">

https://user-images.githubusercontent.com/63787525/115609761-90f5c580-a2ad-11eb-9588-f261d480b681.mov

**Comment by hgiesel** [comment]
Duplicate: https://github.com/ijgnd/anki__editor__apply__font_color__background_color__custom_class__custom_style/issues/46

This will probably be fixed in one of the upcoming Anki versions.

**Comment by chrisnerio** [comment]
> Duplicate: #46
> 
> This will probably be fixed in one of the upcoming Anki versions.

Any idea when it will come or if there's a fix? It's been over a year with multiple updates
