### ISSUE TITLE
shorten the red box?

### ISSUE THREAD

**Issue by ankidoc** [ijgnd/anki__editor__apply__font_color__background_color__custom_class__custom_style#54]
Is there any way that one can make the red box smaller and not over the whole  flashcard width?

**Comment by hgiesel** [comment]
Which red box?

**Comment by ankidoc** [comment]
![CleanShot 2021-11-18 at 15 50 39](https://user-images.githubusercontent.com/81517565/142438554-eb3c67e2-7f3c-4fdb-b04b-5becd090b806.png)
![CleanShot 2021-11-18 at 15 51 15](https://user-images.githubusercontent.com/81517565/142438582-0a1f7bea-63a4-401e-8f1f-edb3da47732a.png)

So when the content is little like just a short text, then the box is huge in comparison to that. Just wondering if there is anything adaptive or manual shortening of the box.
