### ISSUE TITLE
Change "class" name on all previously produced cards.

### ISSUE THREAD

**Issue by huandney** [ijgnd/anki__editor__apply__font_color__background_color__custom_class__custom_style#57]
hi,
Is there any way we can change the name of the "class", for example, from `<div class="red_box">` to `<div class="test">`, and that changes in all cards already made?

Thanks.

**Comment by hgiesel** [comment]
You could use the built-in Find and Replace functionality. Just replace `class="red_box"` with `class="test"`

**Comment by huandney** [comment]
I didn't know about this feature, thank you very much!.
